 platform :ios, '9.0'

target 'CYMusic' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod ‘Masonry’
  pod ‘YYModel’


  # Pods for CYMusic

end
